/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MessageBody: typeof import('./components/MessageBody.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NText: typeof import('naive-ui')['NText']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const MessageBody: typeof import('./components/MessageBody.vue')['default']
  const NAvatar: typeof import('naive-ui')['NAvatar']
  const NButton: typeof import('naive-ui')['NButton']
  const NConfigProvider: typeof import('naive-ui')['NConfigProvider']
  const NDialogProvider: typeof import('naive-ui')['NDialogProvider']
  const NDropdown: typeof import('naive-ui')['NDropdown']
  const NForm: typeof import('naive-ui')['NForm']
  const NFormItem: typeof import('naive-ui')['NFormItem']
  const NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
  const NInput: typeof import('naive-ui')['NInput']
  const NLayout: typeof import('naive-ui')['NLayout']
  const NLayoutContent: typeof import('naive-ui')['NLayoutContent']
  const NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
  const NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
  const NLayoutSider: typeof import('naive-ui')['NLayoutSider']
  const NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
  const NMenu: typeof import('naive-ui')['NMenu']
  const NMessageProvider: typeof import('naive-ui')['NMessageProvider']
  const NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
  const NText: typeof import('naive-ui')['NText']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}