export { api } from './instance'
export { logout } from './auth'
export { login } from './generated/services/authenticateController'
export { me, register } from './generated/services/usersController'
export type * from './generated/components'
