-- Stop the application and back up the database first.
-- Apply 001-message-persistence.sql before this script on legacy databases.
-- Seed conversation 0 before Hibernate adds the messages -> conversations FK.
BEGIN;
CREATE TABLE IF NOT EXISTS conversations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6),
    updated_at timestamp(6)
);
INSERT INTO conversations (id, created_at, updated_at)
SELECT 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM conversations WHERE id = 0);
-- Membership is unique per chatroom/user, rather than per user globally.
-- Hibernate creates the remaining new tables, indexes and composite constraint.
ALTER TABLE IF EXISTS chatroom_members DROP CONSTRAINT IF EXISTS unique_user_id;
COMMIT;
